name: 自动部署
# 当有改动推送到master分支时，启动Action
on:
  push:
    branches:
      - master
      #2020年10月后github新建仓库默认分支改为main，注意更改
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v5
      with:
        ref: master

    - name: 安装 Node
      uses: actions/setup-node@v4
      with:
        node-version: "22.x" #action使用的node版本，建议大版本和本地保持一致。可以在本地用node -v查询版本号。

    - name: 安装 Hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g

    - name: 缓存 Hexo
      uses: actions/cache@v4
      id: cache
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: 安装依赖
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install --save

    - name: 生成静态文件
      run: |
        hexo clean
        hexo generate
        hexo douban
        gulp
        gulp pwa

    - name: 部署
      run: |
        git clone https://github.com/Waynenet/Waynenet.github.io.git deploy-repo
        cd deploy-repo
        git checkout main

        # 清空仓库，但保留以下关键文件和目录：
        find . -path ./.git -prune -o \
               -path ./.github -prune -o \
               -name 'README.md' -prune -o \
               -exec rm -rf {} \; 2> /dev/null

        # 复制 public 内容（-n 避免覆盖已保留的文件）
        cp -rn ../public/* .

        git config user.name 'Waynenet'
        git config user.email '54445994+Waynenet@users.noreply.github.com'
        git add -A

        if git diff-index --quiet HEAD --; then
          echo "没有变更，无需提交"
        else
          git commit -m "${{ github.event.head_commit.message }} $(date +"%Z %Y-%m-%d %A %H:%M:%S") 增量更新 By Github Actions"
          git push "https://Waynenet:${{ secrets.HEXO }}@github.com/Waynenet/Waynenet.github.io.git" main
        fi
